export enum ORDER_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  PREPARING = "PREPARING",
  READY = "READY",
  COLLECTED = "COLLECTED",
  CANCELLED = "CANCELLED",
}

export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  INSTITUTION_ADMIN = "INSTITUTION_ADMIN",
  CANTEEN_OWNER = "CANTEEN_OWNER",
  CANTEEN_STAFF = "CANTEEN_STAFF",
  STUDENT = "STUDENT",
}
